.TH IPK-CLIENT 1
.SH NAME
ipk-client \- client for computing mathematic tasks
.SH SYNOPSIS
.B ipk-client
.IR hostname
.SH DESCRIPTION
.B ipk-client
connects to a server, receives mathematic task, solves it and sends back the result.
.PP
The
.IR hostname
can be valid IPv4 or IPv6 address. Even a domain name is supported.
.PP
The communication between the client and the server is done by sending messages HELLO, SOLVE, RESULT and BYE.
.PP
The client begins the communication by setting up a TCP connection with the server on the port \fI55555\fR.
After that, the client sends the message HELLO \fIid\fR\\n, where \fIid\fR is a md5 hash of the student login.
.PP
The server can answer by the message SOLVE \fInumber\fR \fIoperation\fR \fInumber\fR\\n.
Allowed operations are +, -, *, /.
The client computes the mathematic task and sends the solution in the message RESULT \fIsolution\fR\\n.
If the client is unable to solve the mathematic task (dividing by zero, overflow), it sends the message RESULT ERROR\\n.
.PP
The server can continue by another SOLVE message, or by the message BYE \fIsecret\fR\\n.
The client writes out the value of \fIsecret\fR to the stdout and closes the connection.
If the secret is in format UNKNOWN, it means, that the server was unable to identify the entered login sent in HELLO messsage.
.SH RETURN VALUE
On success, the program returns EXIT_SUCCESS. If an error occurs, the program returns EXIT_FAILURE.
.SH EXAMPLES
Connecting to a public server:
.PP
.nf
.RS
ipk-client 147.229.13.210
ipk-client 2001:67c:1220:80c::93e5:dd2
ipk-client pcgregr.fit.vutbr.cz
.RE
.fi
.PP
Connecting to the localhost:
.PP
.nf
.RS
ipk-client 127.0.0.1
ipk-client ::1
ipk-client localhost
.RE
.fi
.PP
.SH BUGS
If the server unexpectedly closes the connection, the client will be still waiting for the BYE message ad infinitum.
.PP
At the same time, the client can respond only to one valid message from the server, even if it receives more than one at once.
.SH AUTHOR
Written by Marek Jankech.